// Export components (optional)
export { default as Navbar } from './Navbar'
export { default as ThemeToggle } from './ThemeToggle'
export { default as Hero } from './Hero'
export { default as About } from './About'
export { default as Projects } from './Projects'
export { default as Experience } from './Experience'
export { default as Contact } from './Contact'
export { default as Footer } from './Footer'
export { default as BackgroundAnimation } from './BackgroundAnimation'
